/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as EditorsRouteImport } from './routes/editors'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as EditorsSlugRouteImport } from './routes/editors.$slug'
import { Route as CoursesSlugRouteImport } from './routes/courses.$slug'
import { Route as ApiPublicEnrollRouteImport } from './routes/api/public/enroll'

const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorsRoute = EditorsRouteImport.update({
  id: '/editors',
  path: '/editors',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoursesRoute,
} as any)
const EditorsSlugRoute = EditorsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EditorsRoute,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CoursesRoute,
} as any)
const ApiPublicEnrollRoute = ApiPublicEnrollRouteImport.update({
  id: '/api/public/enroll',
  path: '/api/public/enroll',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRouteWithChildren
  '/editors': typeof EditorsRouteWithChildren
  '/portfolio': typeof PortfolioRoute
  '/reviews': typeof ReviewsRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/editors/$slug': typeof EditorsSlugRoute
  '/courses/': typeof CoursesIndexRoute
  '/api/public/enroll': typeof ApiPublicEnrollRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/editors': typeof EditorsRouteWithChildren
  '/portfolio': typeof PortfolioRoute
  '/reviews': typeof ReviewsRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/editors/$slug': typeof EditorsSlugRoute
  '/courses': typeof CoursesIndexRoute
  '/api/public/enroll': typeof ApiPublicEnrollRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRouteWithChildren
  '/editors': typeof EditorsRouteWithChildren
  '/portfolio': typeof PortfolioRoute
  '/reviews': typeof ReviewsRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/editors/$slug': typeof EditorsSlugRoute
  '/courses/': typeof CoursesIndexRoute
  '/api/public/enroll': typeof ApiPublicEnrollRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/courses'
    | '/editors'
    | '/portfolio'
    | '/reviews'
    | '/courses/$slug'
    | '/editors/$slug'
    | '/courses/'
    | '/api/public/enroll'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/editors'
    | '/portfolio'
    | '/reviews'
    | '/courses/$slug'
    | '/editors/$slug'
    | '/courses'
    | '/api/public/enroll'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/courses'
    | '/editors'
    | '/portfolio'
    | '/reviews'
    | '/courses/$slug'
    | '/editors/$slug'
    | '/courses/'
    | '/api/public/enroll'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  CoursesRoute: typeof CoursesRouteWithChildren
  EditorsRoute: typeof EditorsRouteWithChildren
  PortfolioRoute: typeof PortfolioRoute
  ReviewsRoute: typeof ReviewsRoute
  ApiPublicEnrollRoute: typeof ApiPublicEnrollRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editors': {
      id: '/editors'
      path: '/editors'
      fullPath: '/editors'
      preLoaderRoute: typeof EditorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/editors/$slug': {
      id: '/editors/$slug'
      path: '/$slug'
      fullPath: '/editors/$slug'
      preLoaderRoute: typeof EditorsSlugRouteImport
      parentRoute: typeof EditorsRoute
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/api/public/enroll': {
      id: '/api/public/enroll'
      path: '/api/public/enroll'
      fullPath: '/api/public/enroll'
      preLoaderRoute: typeof ApiPublicEnrollRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CoursesRouteChildren {
  CoursesSlugRoute: typeof CoursesSlugRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesSlugRoute: CoursesSlugRoute,
  CoursesIndexRoute: CoursesIndexRoute,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

interface EditorsRouteChildren {
  EditorsSlugRoute: typeof EditorsSlugRoute
}

const EditorsRouteChildren: EditorsRouteChildren = {
  EditorsSlugRoute: EditorsSlugRoute,
}

const EditorsRouteWithChildren =
  EditorsRoute._addFileChildren(EditorsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  CoursesRoute: CoursesRouteWithChildren,
  EditorsRoute: EditorsRouteWithChildren,
  PortfolioRoute: PortfolioRoute,
  ReviewsRoute: ReviewsRoute,
  ApiPublicEnrollRoute: ApiPublicEnrollRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
