// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}


function createSupabaseClient() {
  // Try NEXT_PUBLIC prefix for Vercel/Next-style deployments
  // Then fall back to VITE_SUPABASE_URL (standard for Vite) or Lovable Cloud defaults
  const SUPABASE_URL = 
    (typeof process !== 'undefined' ? process.env['NEXT_PUBLIC_SUPABASE_URL'] : undefined) ||
    import.meta.env['VITE_SUPABASE_URL'] || 
    (typeof process !== 'undefined' ? process.env['SUPABASE_URL'] : undefined);
    
  const SUPABASE_PUBLISHABLE_KEY = 
    (typeof process !== 'undefined' ? process.env['NEXT_PUBLIC_SUPABASE_ANON_KEY'] : undefined) ||
    import.meta.env['VITE_SUPABASE_PUBLISHABLE_KEY'] || 
    (typeof process !== 'undefined' ? process.env['SUPABASE_PUBLISHABLE_KEY'] : undefined);

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud or set NEXT_PUBLIC_SUPABASE_URL/NEXT_PUBLIC_SUPABASE_ANON_KEY.`;
    console.error(`[Supabase] ${message}`);
    // Only throw in development/SSR to prevent crashing the whole client bundle if keys are expected to be injected later
    if (import.meta.env.DEV) {
       console.warn("Supabase client initialized without keys. This is normal during build time if keys are injected at runtime.");
    }
  }

  return createClient<Database>(SUPABASE_URL || '', SUPABASE_PUBLISHABLE_KEY || '', {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY || ''),
    },
    auth: {
      storage: typeof window !== 'undefined' ? window.localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

